title: Affordance Imagnation Dictionary
description: Project page for physical simulation-based affordance imagination of objects
theme: jekyll-theme-cayman
baseurl: /affordance-imagination-dictionary
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
